# Navigation Links
#   To link a homepage widget, specify the URL as a hash `#` followed by the filename of the
#     desired widget in your `content/home/` folder.
#   The weight parameter defines the order that the links will appear in.

main:
  - name: Home
    url: /
    weight: 10
  - name: Gallery
    url: gallery
    weight: 60
  - name: News
    url: post
    weight: 40
  - name: People
    url: people
    weight: 30
  - name: Positions
    url: position
    weight: 50
  - name: Research
    url: research
    weight: 20
#  - name: Publications
#    url: publication
#    weight: 70
  - name: Contact
    url: contact
    weight: 80
